replicaCount: 2

image:
  repository: nginx
  tag: "1.25.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: "my-og-ip"   # set your static IP name
  hosts:
    - host: "microservice.example.com"
      paths:
        - path: /
          pathType: Prefix
  tls: [] # example if you later enable cert-manager
  # - secretName: microservice-tls
  #   hosts:
  #     - microservice.example.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
